# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: Build
  displayName: 'Build and Test'
  pool:
    vmImage: 'windows-latest'

  steps:
  - checkout: self

  # - task: UsePythonVersion@0
  #   inputs:
  #     versionSpec: '3.x'  # This will be used to download and install Python
  #     addToPath: true

  - script: |
      python --version
    displayName: 'Check Python version'

  - script: |
      python -m pip --version
    displayName: 'Check pip version'

  # - script: |
  #     python -m pip install pytest-allure-adaptor
  #   displayName: 'Install pytest-allure-adaptor'

  - script: |
      pytest.exe test_Donation.py --alluredir=./allure-reports
      allure serve ./allure-reports  
    displayName: 'Run Pytest with Allure'
    workingDirectory: C:\Windows\actions-runner\_work\Connectone_New\Connectone_New\Test_Voucher

  - script: |
      allure serve ./allure-reports 
    displayName: 'Generate Allure Report'

  # - script: |
  #     C:\Python\Scripts\pytest.exe test_BanktoBank.py --html=report.html
  #   displayName: 'Run python script'
  #   workingDirectory: C:\Windows\actions-runner\_work\Connectone_New\Connectone_New\Test_Voucher
