name: Trigger Repository B

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Your Workflow Name in Repo B"]
    types:
      - completed

jobs:
  trigger-repo-b:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repository B
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_B_TOKEN }}
          repository: ShantanuKhanna2/Connectone_New
          event-type: "trigger-repo-b"
